"""Initial Migration

Revision ID: df2981bf24dd
Revises: 
Create Date: 2024-07-11 19:33:37.993767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # noqa: F401
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'df2981bf24dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if published column exists using raw SQL - idempotent migration
    conn = op.get_bind()
    insp = inspect(conn)

    # Add published column only if it doesn't exist
    if 'published' not in [col['name'] for col in insp.get_columns('activity')]:
        op.add_column('activity', sa.Column('published', sa.Boolean(), nullable=False, server_default=sa.true()))

    # If you need to rename columns instead of dropping them, use the rename_column command
    # For example, if we are changing the name 'published_version' to 'published', we would use:
    # op.alter_column('activity', 'published_version', new_column_name='published', existing_type=sa.Boolean())

    # Drop published_version if it exists
    if 'published_version' in [col['name'] for col in insp.get_columns('activity')]:
        op.drop_column('activity', 'published_version')

    # Drop version if it exists
    if 'version' in [col['name'] for col in insp.get_columns('activity')]:
        op.drop_column('activity', 'version')

    # Drop assignment_user_uuid if it exists
    if 'assignment_user_uuid' in [col['name'] for col in insp.get_columns('assignmentusersubmission')]:
        op.drop_column('assignmentusersubmission', 'assignment_user_uuid')

    # Handle trail foreign keys
    constraints = [con['name'] for con in insp.get_foreign_keys('trail')]
    if 'trail_org_id_fkey' in constraints:
        op.drop_constraint('trail_org_id_fkey', 'trail', type_='foreignkey')
    op.create_foreign_key('trail_org_id_fkey', 'trail', 'organization', ['org_id'], ['id'], ondelete='CASCADE')

    if 'trail_user_id_fkey' in constraints:
        op.drop_constraint('trail_user_id_fkey', 'trail', type_='foreignkey')
    op.create_foreign_key('trail_user_id_fkey', 'trail', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trail_org_id_fkey', 'trail', type_='foreignkey')
    op.create_foreign_key('trail_org_id_fkey', 'trail', 'organization', ['org_id'], ['id'])
    op.drop_constraint('trail_user_id_fkey', 'trail', type_='foreignkey')
    op.create_foreign_key('trail_user_id_fkey', 'trail', 'user', ['user_id'], ['id'])

    op.add_column('assignmentusersubmission', sa.Column('assignment_user_uuid', sa.VARCHAR(), autoincrement=False, nullable=False))

    op.add_column('activity', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False, server_default=sa.text('1')))
    op.add_column('activity', sa.Column('published_version', sa.INTEGER(), autoincrement=False, nullable=False, server_default=sa.text('1')))
    op.drop_column('activity', 'published')
    # ### end Alembic commands ###

